# https://snapcraft.io/docs/snapcraft-yaml-reference
name: circleoffifths # you probably want to 'snapcraft register <name>'
title: circleoffifths
base: core18 # the base snap is the execution environment for this snap
version: 1.0.0 # just for humans, typically '1.2+git' or '1.3.2'
summary: %{Summary} # 79 char long summary
description: |
    %{DESCRIPTION}
confinement: devmode
grade: devel

apps:
    circleoffifths:
        command: python3 -m circleoffifths.__main__

parts:
    circleoffifths:
        plugin: python
        source: .
        python-version: python3
